### PR TITLE
add besue box

### PR DESCRIPTION
**Pull request by EmanHerawy**
add hyperledger besu drizzle truffle box

### CODE REVIEW

**Comment by DiscRiskandBisque** [comment]
Hi @EmanHerawy! Sorry for the late response. Thank you for this I'm excited to check it out.

@cds-amal @kevinbluer When one of you gets a chance can you review this so we can add it?

**Comment by EmanHerawy** [comment]
Hi @cds-amal  I have updated my repo with the required fixes  
@DiscRiskandBisque  Thank you :)

**Comment by cds-amal** [comment]
Hi @EmanHerawy 

[These metadata changes](https://github.com/EmanHerawy/besu-drizzle-truffle-box/commit/f1f5664a7d639bf42f1128e854bdbe4b67f59d23#commitcomment-41555275) should be in the [`besu` PR branch of your TruffleSuite.com fork](https://github.com/EmanHerawy/trufflesuite.com/blob/besu-box/src/data/boxes.json).

The metadata is used by the main website to [present community boxes](https://www.trufflesuite.com/boxes). I should have explained it more clearly in my PR comments!

**Comment by EmanHerawy** [comment]
@cds-amal  sorry for the confusion, will fix it now

**Comment by cds-amal** [comment]
Oh wow, that's a lot of changes @EmanHerawy.

Our contribution guide should have explained how to keep a box PR up to date. The merging of develop into the PR branch hides the two important contributions you made among many many unrelated commits. I'm not comfortable accepting this PR as it is. I think the easiest way to proceed is to close this PR and re-submit another one where you make the two changes off of the latest develop branch.

I'm sorry for the inconvenience and made an issue #770 to update our contributor guide to make this process easier.

**Pull request closed without merging**
