### PR TITLE
added warning about conflict between contract names and node objects

### PR DESCRIPTION
**Pull request by mktcode**
referring to: https://github.com/trufflesuite/truffle/issues/3329

image

### CODE REVIEW

**Comment by eggplantzzz** [comment]
Thanks again @mktcode! Let me take a look and get back to you.

**Comment by eggplantzzz** [comment]
I have 2 comments about this. I feel like this should be a **Note:** rather than the red warning box.

I feel like the messaging should be slightly different. I think we should try to communicate 2 things to people:
  - your contract names get loaded as variables into the console context
  - for this reason avoid names that might conflict with Node native objects like Buffer or String

What do you think?

**Comment by mktcode** [comment]
What about a note regarding a future release? That was the whole point for me because I was told that a fix for this issue, by implementing some namespacing mechanic, will probably not happen until the next major release. So I thought it might be a good idea to put a note in the docs.

> Your contract names get loaded as variables into the console context. For this reason it is recommended to avoid names that might conflict with Node's native objects like Buffer or String. For updates see the related [issue on GitHub](https://github.com/trufflesuite/truffle/issues/3329).

Better?

**Comment by eggplantzzz** [comment]
I like it! I think that should be helpful.

**Comment by mktcode** [comment]
Updated. :)

**Comment by eggplantzzz** [comment]
Thanks @mktcode!

**Review by eggplantzzz — APPROVED** [review]

**Review by cds-amal — APPROVED** [review]
LGTM!

**Review by mizz75 — COMMENTED** [review]
Hi

**Pull request merged**
