### PR TITLE
Updated userOrg for BSC-Truffle-Starter-Box

### PR DESCRIPTION
**Pull request by RumeelHussainbnb**
Updated the userOrg to bnb-chain
updated repo link: https://github.com/bnb-chain/BSC-Truffle-Starter-Box
truffle listing: https://trufflesuite.com/boxes/BSC-Truffle-Starter-Box/

### CODE REVIEW

**Review by cds-amal — APPROVED** [review]
Thanks for the update @RumeelHussainbnb. Please note, your box repo does not conform to our box-image criteria. I've [pushed a PR](https://github.com/bnb-chain/BSC-Truffle-Starter-Box/pull/1) to address it, please review when you have a moment.

**Comment by RumeelHussain** [comment]
Can you please share the Box Image Criteria ? 
image


Please update the Unbox command here as well:  
https://trufflesuite.com/boxes/BSC-Truffle-Starter-Box/

**Comment by cds-amal** [comment]
>Can you please share the Box Image Criteria ?

@RumeelHussain, see [this link for box assets](https://trufflesuite.com/boxes/blueprint/). Note, the PR you merged [took care of renaming the images to what is expected](https://github.com/bnb-chain/BSC-Truffle-Starter-Box/commit/46aa0c4fa02e345fa8f06cf9d187147669fac9e1).

My understanding is BSC-Starter-Box details is sourced from [bnb-chain/BSC-Truffle-Starter-Box's Readme.md](https://github.com/bnb-chain/BSC-Truffle-Starter-Box/blob/master/README.md) file though, I'm not certain why our site is out of sync. @kevinbluer, would know more.

**Comment by cds-amal** [comment]
@RumeelHussain [looks like the updated readme is correct](https://trufflesuite.com/boxes/BSC-Truffle-Starter-Box/#installation)

**Pull request merged**
