### PR TITLE
Pass number as string to avoid exception

### PR DESCRIPTION
**Pull request by ilovehackathons**
`web3.utils.toWei(1,"ether")` throws an exception:

> Please pass numbers as strings or BN objects to avoid precision errors.

Corrected to `web3.utils.toWei("1","ether")`.

### CODE REVIEW

**Review by eggplantzzz — APPROVED** [review]
yep this is a thing, I like it

**Comment by haltman-at** [comment]
Hey, it looks like this PR has a merge conflict that needs to be resolved. @ilovehackathons, were you planning on handling this?

**Comment by ilovehackathons** [comment]
> Hey, it looks like this PR has a merge conflict that needs to be resolved. @ilovehackathons, were you planning on handling this?

Done!

**Review by haltman-at — APPROVED** [review]
Great, thank you!

**Pull request merged**
