### PR TITLE
Update test command instruction

### PR DESCRIPTION
**Pull request by mehere**
truffle test command should only be run after a network is started

### CODE REVIEW

**Comment by gnidan** [comment]
Thanks for this @mehere! Since this has gone about a year and a half without any attention, I'd say the next step is for someone on our side to verify that this information didn't make into our docs elsewhere. If this is still an omission, I would love to get this merged!

**Comment by haltman-at** [comment]
Sorry about taking so long to get to this!  We think we're going to use the second part of this, but not the first; we don't want to recommend starting up a separate Ganache instance as the default way to use Truffle Test.

**Comment by eggplantzzz** [comment]
And just to be clear on this one, you don't need to start a network separately for `truffle test` in the cases where you don't have networks named "test" or "development" in your `truffle-config.js`.

**Comment by eggplantzzz** [comment]
I took this work and tweaked it and put in a more up-to-date PR [here](https://github.com/trufflesuite/trufflesuite.com/pull/198). Closing this in favor of that one. Thanks @mehere!

**Pull request closed without merging**
