### PR TITLE
 Add tutorial describing how to use scribble with truffle

### PR DESCRIPTION
**Pull request by JoranHonig**
Hey all 👋 

I wrote a short tutorial that shows you how you can use Scribble to upgrade your unit test suite. I hope this is perfect content for the truffle tutorial website!

### CODE REVIEW

**Review by cds-amal — CHANGES_REQUESTED** [review]
Oops, meant to say I have to integrate it. I'll push changes to your repo

**Review by cds-amal — APPROVED** [review]
🎉 Thanks @JoranHonig !

**Review by leeftk — COMMENTED** [review]
Looks great to me. Approved.

**Comment by JoranHonig** [comment]
Now CI seems to be blocked 😅

**Comment by kevinbluer** [comment]
Yup, CI currently having some issues 🤦 Looks great though + just merged. Only quirk was with the [date](https://github.com/trufflesuite/trufflesuite.com/pull/1056/commits/57b8b916cd7ba1d033892cb497ebeff58602da30#diff-4b02122c1b08bb27b154845355b0735369ca00671b762852954eb87b01d9c9d6R4), which I'll adjust before pushing live in a moment 👍

**Pull request merged**
