### PR TITLE
Remove all references to Corda in Ganache UI

### PR DESCRIPTION
**Pull request by jeffsmale90**

### CODE REVIEW

**Review by cds-amal — CHANGES_REQUESTED** [review]
Hey @jeffsmale90 , I noticed that some corda assets show up in the search. Can these be removed from the index? 
image

**Comment by jeffsmale90** [comment]
> Hey @jeffsmale90 , I noticed that some corda assets show up in the search. Can these be removed from the index?

Good call @cds-amal - I feel uncomfortable removing historic blog posts, but agree that it's a little confusing. I discussed with @davidmurdoch and have added deprecation notices on the blog posts that talk about Corda directly (there's a couple that _mention_ it, and link to these blog posts, where I have _not_ added the banner, ie. "2020 is Finally Over - A Year End Wrapup".

Let me know if you think this is sufficient, or if you feel we should do something different.

Thanks!

**Comment by jeffsmale90** [comment]
> Makes sense. weird that fleek build failed. I'll spin this up locally to see how it looks

Yeah - whoops. I accidentally reset the file to `develop` branch, instead of `main` (it doesn't exist in develop).

**Comment by davidmurdoch** [comment]
Looking good. Can you run https://squoosh.app/ on the new pngs? Use optipng for the output at max settings should give decent results.

**Comment by jeffsmale90** [comment]
> Looking good. Can you run https://squoosh.app/ on the new pngs? Use optipng for the output at max settings should give decent results.

Squooshed!

**Review by cds-amal — APPROVED** [review]
Looks good to me

**Pull request merged**
