### PR TITLE
Fix the code block formatting

### PR DESCRIPTION
**Pull request by tbhaxor**

### CODE REVIEW

**Comment by eggplantzzz** [comment]
Thanks @tbhaxor, I confirmed that this fix works!

**Review by cds-amal — DISMISSED** [review]
LGTM @tbhaxor !

**Comment by cds-amal** [comment]
Hello @tbhaxor, There was another submission for this issue 4 days before yours, and we will go with that one. Apologies for that and hope to see more of your contributions.

**Comment by tbhaxor** [comment]
> Hello @tbhaxor, There was another submission, #1173, for this issue 4 days before yours. For fairness, we will go with that one. Apologies for that and hope to see more of your contributions.

There is no need to apologise for this. We all are learners I hope this issue will be fixed soon as while reading docs, it feels like something is breaking. 

I hope you would understand and release the patch asap

**Pull request closed without merging**
