### PR TITLE
Added in mkdocs-minify plugin and setup.

### PR DESCRIPTION
**Pull request by michaeljohnbennett**
did some lighthouse testing once implemented.
Seems to be working as expected.

### CODE REVIEW

**Review by kevinbluer — CHANGES_REQUESTED** [review]
noticed that `/dashboard` isn't rendering...it looks like it's because it's in the `custom_theme` directory which doesn't get passed through the markdown renderer and thus leaves `/assets/stylesheets/dashboard.css` and `/assets/js/dashboard.js` as is (e.g. doesn't append `.min` suffix after minification). one option is we just add that manually so it should "just work"...thoughts?

**Comment by michaeljohnbennett** [comment]
ah ok, I will check that out.

**Comment by michaeljohnbennett** [comment]
fixed imports.

**Comment by kevinbluer** [comment]
awesome @michaeljohnbennett, LGTM now! also nice that we're able to take advantage of the fleek build previews (enabled them at the end of last week), e.g. https://bafybeie4nxwwrpx3pyfb37krwt6lo4p6ccvf56mkn5q4sd6mrx2va5r4ay.on.fleek.co/dashboard/

**Pull request merged**
