### PR TITLE
[Tutorial] Fix a link which points to deprecated repo(truffle-core)

### PR DESCRIPTION
**Pull request by ackintosh**
😉 

Thanks for great documentation!

### CODE REVIEW

**Comment by eggplantzzz** [comment]
@ackintosh Sorry for taking so long to get to this. It looks good to me. If you are still able to resolve the conflict on this then I will try and get it merged. Let me know if you don't have time! Thanks for the PR!

**Comment by ackintosh** [comment]
Yeah, I'll update this PR. 😉

**Comment by ackintosh** [comment]
@eggplantzzz Please have a look when you have time. 🙏

**Comment by eggplantzzz** [comment]
Thanks again @ackintosh! I'll get one other approval and we'll merge.

**Pull request merged**
