### PR TITLE
Update getting started

### PR DESCRIPTION
**Pull request by ogryzek**
Include truffle init in installation

### CODE REVIEW

**Comment by ogryzek** [comment]
I see `truffle init` is mentioned in [Creating a Project](http://truffleframework.com/docs/getting_started/project).

I'm not sure my commit is a _better_ solution, but I found it a little confusing that `truffle develop` didn't work after following [installation](http://truffleframework.com/docs/getting_started/installation), and seeing it in the [next section](http://truffleframework.com/docs/getting_started/client).

**Comment by bmmpxf** [comment]
Hi @ogryzek . Thanks for your suggestion; I see your point. I think it might be clearer if we just switched the order of the sections:

1. Installation
2. Creating a project *(was 3.)*
3. Choosing an Ethereum client *(was 2.)*

I think that might alleviate confusion, and would make sure that people had a project before attempting to run `truffle develop` (assuming they were reading in order). Would that achieve the same goal as your PR?

**Comment by ogryzek** [comment]
@bmmpxf I think that would be perfect!

**Comment by bmmpxf** [comment]
You got it! Done with https://github.com/trufflesuite/trufflesuite.com/commit/ce907472925351a9310ef88d1caaf4ce066bf93e.

**Pull request closed without merging**
