### PR TITLE
Adding 'accessibe' script

### PR DESCRIPTION
**Pull request by kevinbluer**
This PR adds the [Accessibe](https://accessibe.com/) script enabling rolling accessibility audits (and thus ADA, WCAG, etc compliance).

### CODE REVIEW

**Comment by davidmurdoch** [comment]
"Thanks to AI, the dream  of an accessible  web  is finally attainable! "

https://accessibe.com/

I don't like this, it makes me uncomfortable to skirt our responsibility by saying "AI will take care of it". That said, we already are, because our website fails to reach acceptable accessibility goals all over the place.

We wouldn't be okay with "AI" creating our website content for "enabled" or sighted users, I don't think we should we be okay with "AI" doing the same for people with disabilities.

**Comment by davidmurdoch** [comment]
I'm the blocker on this and here is a reason why:

Here is ConsenSys on mobile without (first image) and with (second image) vision impairment enabled. Zero other changes or scrolling. I didn't test other "features".

# Enabling the accessibility tool made the site less accessible.

without:
Screenshot_20220129-132835

with:
Screenshot_20220129-132853

**Comment by kevinweaver** [comment]
I'm not seeing this issue on iOS Safari or Brave.  Are you able to test on other Android browsers to get a sense for impact?

**Comment by davidmurdoch** [comment]
@kevinweaver this further proves my point. This 3rd party software is inconsistent and can change our website in any way it wants to, and it could be different every day, as this software scans the site for new AI-enhanced accessibility fixes, and may apply different ones if the half-baked AI model decides it should.

A human should be involved in accessibility decisions. The issue is that we would be trying to avoid accountability to provide services to people with disabilities. Adding this to our site _screams_ "legal made us do it, we don't really care about you".

And it looks like the largest U.S. Blind Advocacy Group agrees with me:

> the Board of Directors reviewed accessiBe’s business practices at the urging of members who have researched and interacted with the company, and the Board believes that accessiBe currently engages in behavior that is harmful to the advancement of blind people in society.

https://www.forbes.com/sites/gusalexiou/2021/06/26/largest-us-blind-advocacy-group-bans-web-accessibility-overlay-giant-accessibe/?sh=10c9b1c55a15

**Comment by jlazoff** [comment]
**Adding information regarding the AI capabilities of accessiBe, provided by the Consensys account manager:**

Here are a few resources you can share with the TruffleSuite Dev. 

- [in-depth technical demo](https://ssp.accessibe.com/t/103559/c/1ad7bae5-c51d-4cd0-a3e5-5b9198deeae3/NB2HI4DTHIXS653XO4XHS33VOR2WEZJOMNXW2L3XMF2GG2B7OY6VAUJYONMGS4SFNNBUS===/www-youtube-com-watch) by our CEO.
- Technology Overview (attached)
- I am happy to get on a call with him and answer his questions if you'd like. 

The bottom line is that web accessibility is measurable and observable. Anyone can use our UI and see how it helps a wide spectrum of people with disability control how they see a website. Our AI facilitates keyboard navigation and creates alt tags where none existed previously. This technology has its limitations but the improvements it makes represent a huge leap forward in accessibility for end-users. This can be tested, measured, seen, scanned. 

As far as the anti-accessibe article. Here are a few things to note:

Controversy is so easily created when a one-sided opinion piece is published online inevitably originating from people that are deeply invested in the manual remediation industry. An industry within which accessiBe has caused tremendous disruption and whose economic viability is threatened by a technological leap forward. This is the kind of backlash every technological advancement faces when it is in its infancy (ex: I am sure the key players in blockchain technology faced similar negative press). As the market leaders and innovators of this technology, we bear the brunt of the criticism in the media.  

As an account executive at accessiBe I speak with teams of developers every day from large multinational corporations that represent some of the most popular brands in the world (ex: [GE.com](http://ge.com/), [Dannon.com](http://dannon.com/), [Oreo.com](http://oreo.com/),...). They ask me detailed technical questions, which I answer, and then all of them sign up for our 7-day free trial and test the solution thoroughly on their dev sites. After that, they ask me a bunch of additional technical questions, which I am happy to answer. Finally, they test the product some more, and typically by the end of this process, they buy our solution and then remain our client. How could that happen unless accessiBe was proven to be an effective accessibility solution? How could accessiBe experience such exponential growth if its product didn’t deliver on its promises? 

More importantly, millions of people with disabilities have benefited from the tangible and demonstrable accessibility that accessiBe has helped to provide and there are countless testimonials online to verify these experiences. Beyond that, we have many nonprofit organizations that serve people with disabilities that use accessiBe including the National Federation for the Blind in the UK.
- [https://www.nfbuk.org/](https://ssp.accessibe.com/t/103559/c/1ad7bae5-c51d-4cd0-a3e5-5b9198deeae3/NB2HI4DTHIXS653XO4XG4ZTCOVVS433SM4XQ====/www-nfbuk-org)
- [https://www.nationalmssociety.org/](https://ssp.accessibe.com/t/103559/c/1ad7bae5-c51d-4cd0-a3e5-5b9198deeae3/NB2HI4DTHIXS653XO4XG4YLUNFXW4YLMNVZXG33DNFSXI6JON5ZGOLY=/www-nationalmssociety-org)
- [https://www.parkinson.ca/](https://ssp.accessibe.com/t/103559/c/1ad7bae5-c51d-4cd0-a3e5-5b9198deeae3/NB2HI4DTHIXS653XO4XHAYLSNNUW443PNYXGGYJP/www-parkinson-ca)
- [https://gbr.orbis.org/en](https://ssp.accessibe.com/t/103559/c/1ad7bae5-c51d-4cd0-a3e5-5b9198deeae3/NB2HI4DTHIXS6Z3COIXG64TCNFZS433SM4XWK3Q=/gbr-orbis-org-en)

Let me know what else I can do to help.

**Comment by gnidan** [comment]
@jlazoff please do not post links that unnecessarily use tracking URLs

**Comment by gnidan** [comment]
Closing this until someone can provide an unbiased argument that suggests AI-powered accessibility overlays are in fact helpful, since there are numerous resources that indicate that these overlays are useless at best, harmful at worst.

Besides the Forbes article @davidmurdoch posted, [this statement](https://nfb.org/about-us/press-room/national-convention-sponsorship-statement-regarding-accessibe) by the NFB suggests that accesiBe in particular is "harmful to the advancement of blind people in society", and this [Overlay Fact Sheet](https://overlayfactsheet.com/) is chock-full of critiques to suggest that AI-powered accessibility overlays provide compliance instead of actually benefitting disabled persons.

Happy to discuss this over Zoom if you find this forum insufficient for discourse around this topic.

**Comment by jlazoff** [comment]
Hi @gnidan @davidmurdoch and @kevinbluer ,

If you are interested in learning more about accessiBe to re-assess it's integration on your site, I recommend having a zoom directly with our accessiBe account manager. I am not their sales person... just a middle man, with good experience with accessiBe. 

Let me know and I can setup a zoom meeting or email thread for you to deep dive with their team and ensure all your questions are answered.

**Comment by gnidan** [comment]
Sorry for you to get in the crossfire @jlazoff

**Comment by jlazoff** [comment]
> Sorry for you to get in the crossfire @jlazoff

@gnidan no worries, accessiBe is used by the largest and best sites.

Two things I have noticed: 

1. most sites never end up implementing accessibility. AccessiBe does a good job of remediating this. 

2. The widget adds functionality that is specific to different disabilities. See mesh.xyz or metamask.io for example. 

This takes you from native code accessibility (which we have already submitted a PR for based on the accessiBe audit and SEO report), to providing features that surpass the standards. 

If you are open, I think a zoom or email chat with accessiBe would be great. They are very friendly and have deep technical expertise. They often get questions such as the ones your team is concerned with. 

My team has installed and sometimes we customize the widget, to ensure it's integrated nicely. 

There is also monthly and yearly payment plans, so we can do a trial period if that is more comfortable. 

Let me know what you think 🤔

**Pull request closed without merging**
