### PR TITLE
broken header fix / temp removing gh stars

### PR DESCRIPTION
**Pull request by kevinbluer**
- header formatting
- temporarily removing stars

### CODE REVIEW

**Review by cds-amal — COMMENTED** [review]
The boxes header images looks slightly off, do the images need to be updated @kevinbluer ?

**Comment by kevinbluer** [comment]
hey @cds-amal, apologies totally missed this comment at the time...any chance you could provide an example of "slightly off"? given this PR shifts the image to a css background (vs an inline `img`) it might mean some of the images are a bit trimmed

**Comment by leeftk** [comment]
I did my best to try and fix this issue but it seems like the issue is actually with the images for the boxes not being at the specified size in the instructions which is causing the small discrepancies between the different cards. I say let's merge this since its better than having missing images and then we'll as Bryan to change the sizes of the images so they're all the same.

**Review by leeftk — APPROVED** [review]
LGTM!!!!!

**Pull request merged**
