### PR TITLE
devcon 5 is back baby

### PR DESCRIPTION
**Pull request by kevinbluer**

### CODE REVIEW

**Review by cds-amal — COMMENTED** [review]
How should this be tested @kevinbluer ? 

When I launch it locally, only one page (summary) is accessible

**Comment by kevinbluer** [comment]
Thanks again for reviewing this one @cds-amal (and apologies for the delay in follow-up). From my understanding, the intention was just for this to put it back "as is" meaning pages make not be linked from anywhere, although still accessible...e.g. can you see the following: `/devcon5/ganache-ui-1.html`?

**Comment by davidmurdoch** [comment]
Can this be merged?

**Comment by kevinbluer** [comment]
Good from my side ✅

**Pull request merged**
